In [7]:
class Student:
    def __init__(self, name, grade):
        self.name = name
        self.grade = grade

    def display(self):
        print(f"Name: {self.name}, Grade: {self.grade}")

student1 = Student("Alice", "A")
student1.display()

Name: Alice, Grade: A

In [8]:
class Student:
    def __init__(self, name, grade):
        self.name = name
        self.grade = grade

    def display(self):
        print(f"Name: {self.name}, Grade: {self.grade}")

# Create 2 student objects
student1 = Student("Albin", "A")
student2 = Student("Anu", "B")

# Display details of each student
student1.display()
student2.display()

Name: Albin, Grade: A
Name: Anu, Grade: B

In [9]:
class Consumer:
    def __init__(self, name, city):
        self.name = name
        self.city = city

    def display(self):
        print(f"Name: {self.name}, City: {self.city}")


# Create 5 consumer objects
consumer1 = Consumer("Ramu", "Mumbai")
consumer2 = Consumer("Devajith", "Delhi")
consumer3 = Consumer("John", "Chennai")
consumer4 = Consumer("kate", "Bangalore")
consumer5 = Consumer("Kiran", "Kolkata")

# Display details of each consumer
consumer1.display()
consumer2.display()
consumer3.display()
consumer4.display()
consumer5.display()

Name: Ramu, City: Mumbai
Name: Devajith, City: Delhi
Name: John, City: Chennai
Name: kate, City: Bangalore
Name: Kiran, City: Kolkata